### ISSUE TITLE
how to preprocessing image before feeding AI model?

### ISSUE THREAD

**Issue by KennyTC** [zezo357/pytorch_lite#17]
In pytorch model, I am using `transform`, as follows:
```
"loader = transforms.Compose([
        transforms.Resize(225),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([x, x, x], [x, x, x])
    ])
```
How can I transform this code into Flutter before feeding the AI model?

**Comment by zezo357** [comment]
You can use an image package to transform your image before sending them to my package, 

The only processing I do on images is just scaling to match the model inputs.

**Comment by zezo357** [comment]
No need for tensors, if I remember correctly it should be image bytes, I handle the tensors from my side too

Yes no need to normalize the image

**Comment by KennyTC** [comment]
I used the following to resize and center crop. Its input is the path of image (taken by ImagePicker)

```
Uint8List preprocessImage(String imagePath) {
  // Load the image
  final File imageFile = File(imagePath);
  final Uint8List imageBytes = imageFile.readAsBytesSync();
  final img.Image? image = img.decodeImage(imageBytes);

  // Resize the image
  final Image resizedImage =
      imageLib.copyResize(image!, width: 225, height: 225);

  // Center crop the image
  final int centerX = (resizedImage.width - 224) ~/ 2;
  final int centerY = (resizedImage.height - 224) ~/ 2;
  final Image croppedImage = imageLib.copyCrop(
    resizedImage,
    x: centerX,
    y: centerY,
    width: 224,
    height: 224,
  );

  // Convert image to Uint8List
  final Uint8List processedBytes = croppedImage.getBytes();

  return processedBytes;
}
```

I call getImagePrediction as follows: 

```
List<double> means = [0.485, 0.456, 0.406]
List<double> std = [0.229, 0.224,0.225];
final Uint8List processedImage = preprocessImage(_file.path);
String? _imagePrediction = await _imageModel!.getImagePrediction(processedImage,mean:means,std:std);
```
Then, the following errors appeared when executing the `getImagePrediction` function. 
```
D/OpenGLRenderer(  954): --- Failed to create image decoder with message 'unimplemented'
E/PytorchLitePlugin(  954): error reading image
E/PytorchLitePlugin(  954): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/PytorchLitePlugin(  954): 	at com.zezo357.pytorch_lite.PytorchLitePlugin.getImagePredictionList(PytorchLitePlugin.java:155)
E/PytorchLitePlugin(  954): 	at com.zezo357.pytorch_lite.Pigeon$ModelApi$-CC.lambda$setup$2(Pigeon.java:193)
E/PytorchLitePlugin(  954): 	at com.zezo357.pytorch_lite.Pigeon$ModelApi$$ExternalSyntheticLambda2.onMessage(Unknown Source:2)
E/PytorchLitePlugin(  954): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0$io-flutter-embedding-engine-dart-DartMessenger$SerialTaskQueue(DartMessenger.java:163)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/PytorchLitePlugin(  954): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/PytorchLitePlugin(  954): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/PytorchLitePlugin(  954): 	at java.lang.Thread.run(Thread.java:1012)
E/PytorchLitePlugin(  954): error classifying image
E/PytorchLitePlugin(  954): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/PytorchLitePlugin(  954): 	at org.pytorch.torchvision.TensorImageUtils.bitmapToFloat32Tensor(TensorImageUtils.java:50)
E/PytorchLitePlugin(  954): 	at com.zezo357.pytorch_lite.PytorchLitePlugin.getImagePredictionList(PytorchLitePlugin.java:172)
E/PytorchLitePlugin(  954): 	at com.zezo357.pytorch_lite.Pigeon$ModelApi$-CC.lambda$setup$2(Pigeon.java:193)
E/PytorchLitePlugin(  954): 	at com.zezo357.pytorch_lite.Pigeon$ModelApi$$ExternalSyntheticLambda2.onMessage(Unknown Source:2)
E/PytorchLitePlugin(  954): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.flush(DartMessenger.java:173)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue.lambda$dispatch$0$io-flutter-embedding-engine-dart-DartMessenger$SerialTaskQueue(DartMessenger.java:163)
E/PytorchLitePlugin(  954): 	at io.flutter.embedding.engine.dart.DartMessenger$SerialTaskQueue$$ExternalSyntheticLambda0.run(Unknown Source:2)
```

Can you help me with this?

**Comment by zezo357** [comment]
Can you try saving the image as a file and resending the saved bytes? And let me know 


I think the code can't get the image width and height from the bytes

**Comment by KennyTC** [comment]
@zezo357 I save the image to file, and read it again using the following, but it did not work. 

```
List<double> means = [0.485, 0.456, 0.406]
List<double> std = [0.229, 0.224,0.225];
final Uint8List processedImage = preprocessImage(_file.path);

final directory = await getApplicationDocumentsDirectory();
File temp = File("${directory.path}/test.jpg");
await temp.writeAsBytes(processedImage);
String? _imagePrediction = await _imageModel!.getImagePrediction(await File(temp.path).readAsBytes(),means:means, std:std);
```

The same error as above

**Comment by zezo357** [comment]
> @zezo357 I save the image to file, and read it again using the following, but it did not work. 
> 
> ```
> List<double> means = [0.485, 0.456, 0.406]
> List<double> std = [0.229, 0.224,0.225];
> final Uint8List processedImage = preprocessImage(_file.path);
> 
> final directory = await getApplicationDocumentsDirectory();
> File temp = File("${directory.path}/test.jpg");
> await temp.writeAsBytes(processedImage);
> String? _imagePrediction = await _imageModel!.getImagePrediction(await File(temp.path).readAsBytes(),means:means, std:std);
> ```
> 
> The same error as above

Okay will check it today, and will let you know if I found a workaround, sorry I am taking time since i am busy these days.

**Comment by KennyTC** [comment]
Glad to hear. It helps me a lot. I have used your library for several AI models without preprocessing. I do not want to change to another library just for this problem. 
Looking forward to your feedback.

**Comment by zezo357** [comment]
Just to speed up my process, can you provide a  one file code sample so I test on it ?

**Comment by KennyTC** [comment]
Sure. My project has a lot of things. But the relevance to current problem are as follows:
1) my `crop_image.dart`
 ```
import 'dart:io';
import 'dart:typed_data';

import 'package:image/image.dart' as img;

Uint8List preprocessImage(String imagePath) {
  // Load the image
  final File imageFile = File(imagePath);
  final Uint8List imageBytes = imageFile.readAsBytesSync();
  final img.Image? image = img.decodeImage(imageBytes);

  // Resize the image
  final img.Image resizedImage =
      img.copyResize(image!, width: 225, height: 225);

  // Center crop the image
  final int centerX = (resizedImage.width - 224) ~/ 2;
  final int centerY = (resizedImage.height - 224) ~/ 2;
  final img.Image croppedImage = img.copyCrop(
    resizedImage,
    x: centerX,
    y: centerY,
    width: 224,
    height: 224,
  );

  print("origin image's size ${image.height}, ${image.width}");
  print("resizedImage's size ${resizedImage.height}, ${resizedImage.width}");
  print("croppedImage's size ${croppedImage.height}, ${croppedImage.width}");
  // Convert image to Uint8List
  final Uint8List processedBytes = croppedImage.getBytes();

  return processedBytes;
}

```

2) My `main.dart`
```
import 'crop_image.dart';
import 'model.dart';

ImagePicker  imagePicker =  ImagePicker();
final _file = await imagePicker.pickImage(source: ImageSource.camera, imageQuality: 5);

List<double> means = [0.485, 0.456, 0.406]
List<double> std = [0.229, 0.224,0.225];
final Uint8List processedImage = preprocessImage(_file.path);

ClassificationModel?   _imageModel =  await BreedModelLoader().model;

final directory = await getApplicationDocumentsDirectory();
File temp = File("${directory.path}/test.jpg");
await temp.writeAsBytes(processedImage);
String? _imagePrediction = await _imageModel!.getImagePrediction(await File(temp.path).readAsBytes(),means:means, std:std);
```

3) my "model.dart"
```
class BreedModelLoader {
  static final BreedModelLoader _singleton = BreedModelLoader._internal();
  late Future<ClassificationModel> _model;
  BreedModelLoader._internal() {
    _model = _loadModel();
  }
  factory BreedModelLoader() {
    return _singleton;
  }

  Future<ClassificationModel> _loadModel() async {
    String path = "assets/models/model.pt";
    ClassificationModel temp_model = await PytorchLite.loadClassificationModel(
        path, 224, 224,
        labelPath: "assets/labels/labels.txt");
    return temp_model;
  }

  Future<ClassificationModel> get model => _model;
}
```

**Comment by zezo357** [comment]
thank you very much, will check it at night and let you know what i found,(hopefully a fix)

**Comment by KennyTC** [comment]
Do you have any update on this? If you found anything, you can share. I am willing to help.

**Comment by zezo357** [comment]
I am very sorry, I am busy these days so I am trying to check it , but I can't find enough time

**Comment by zezo357** [comment]
@KennyTC you forgot to reencode your image this why it was failling
```
  Uint8List preprocessImage(String imagePath) {
    // Load the image
    final File imageFile = File(imagePath);
    final Uint8List imageBytes = imageFile.readAsBytesSync();

    final img.Image? image = img.decodeImage(imageBytes);

    // Resize the image
    final img.Image resizedImage =
        img.copyResize(image!, width: 225, height: 225);

    // Center crop the image
    final int centerX = (resizedImage.width - 224) ~/ 2;
    final int centerY = (resizedImage.height - 224) ~/ 2;
    final img.Image croppedImage = img.copyCrop(
      resizedImage,
      x: centerX,
      y: centerY,
      width: 224,
      height: 224,
    );

    print("origin image's size ${image.height}, ${image.width}");
    print("resizedImage's size ${resizedImage.height}, ${resizedImage.width}");
    print("croppedImage's size ${croppedImage.height}, ${croppedImage.width}");

    // Convert image to Uint8List
    final Uint8List processedBytes =
        img.encodePng(croppedImage).buffer.asUint8List();
    return processedBytes;
  }
```

**Comment by KennyTC** [comment]
Thanks very much. I did not know that. So, the problem is not your library's.

**Comment by zezo357** [comment]
Yes

**Comment by KennyTC** [comment]
Thanks a lot. We are using your library, and want it runnable in Iphone too. If you could support IOS, we will very much appreciate.
